name: Release

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: pip install .
      - run: pip install jinja2
      - run: pip install mkdocs
      - run: pip install mkdocstrings-python
      - run: pip install mkdocs-literate-nav
      - run: pip install mkdocs-section-index
      - run: pip install mkdocstrings
      - run: pip install mkdocs-material
      - run: pip install mkdocs-click
      - run: pip install mkdocs-gen-files
      - run: mkdocs gh-deploy --force
